[project]
name = "project-taskify"
version = "0.1.0"
description = ""
requires-python = ">=3.12,<3.14"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "logfire[fastapi]>=4.40.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.3",
]
