[project]
name = "taskify"
version = "0.1.0"
description = "dependências do backend da aplicação"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.142.2",
    "logfire[fastapi]>=5.1.1",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
    "sqlalchemy[asyncio]>=2.1.1",
    "uvicorn[standard]>=0.54.0",
]

[tool.fastapi]
entrypoint = "main:app"

