"""rename table DoUp to tasks

Revision ID: 2bb15b71ea96
Revises: b458adf3741f
Create Date: 2026-01-18 23:58:05.001346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb15b71ea96'
down_revision: Union[str, None] = 'b458adf3741f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("doup_tasks", "tasks")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("tasks", "doup_tasks")
